<a href="https://colab.research.google.com/github/singhpraveen42599-dotcom/Datasciencelab/blob/main/lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BCSE 1593 – Data Science and Visualization Lab
## NumPy Practice Set

### Case Study: Managing Data for a Smart Campus

The university is planning a **Smart Campus Management System**. Different departments are collecting numerical information such as electricity consumption, student attendance, classroom occupancy, library visits and canteen sales.

You are working as a junior data analyst. Before this information is used for reports and dashboards, you need to organize and analyse it using **NumPy**.

In this practice set, you will work with small datasets similar to the type of data that a real campus system may generate.

### Instructions

- Complete the questions in the given order.
- Write your own NumPy code in the empty cells.
- Try to solve the questions using NumPy operations instead of Python loops.
- Display the output wherever it helps you understand the result.
- Use meaningful variable names.
- Do not change the given data unless a question specifically asks you to create a new array.
- If you get an error, first check the array's **shape, indexing and dimensions**.


## Dataset for the Practice

The following data has been collected from three campus facilities:

- **Academic Block**
- **Library**
- **Hostel**

For the monthly datasets, rows represent months and columns represent facilities.


In [ ]:
import numpy as np

# Monthly electricity consumption in kWh
# Columns: Academic Block, Library, Hostel
monthly_energy = np.array([
    [42000, 18500, 31000],
    [43500, 19200, 31800],
    [44800, 20100, 32500],
    [46200, 21500, 33100],
    [47800, 22100, 34000],
    [49500, 23000, 35200],
    [51000, 23800, 36000],
    [52500, 24600, 37100],
    [51800, 24100, 36500],
    [50200, 23200, 35400],
    [47500, 21800, 33900],
    [45000, 20500, 32500]
])

# Monthly student visits
# Columns: Academic Block, Library, Hostel
monthly_visits = np.array([
    [8200, 5400, 6100],
    [8500, 5600, 6250],
    [8700, 5750, 6400],
    [9100, 5900, 6650],
    [9500, 6200, 6900],
    [9800, 6500, 7200],
    [10200, 6800, 7500],
    [10400, 7000, 7700],
    [10100, 6750, 7450],
    [9600, 6300, 7000],
    [9000, 5900, 6650],
    [8600, 5650, 6350]
])

# Classroom occupancy percentage for one week
# Rows = days, Columns = five classrooms
weekly_occupancy = np.array([
    [72, 68, 81, 75, 63],
    [78, 71, 85, 80, 66],
    [82, 74, 88, 83, 69],
    [76, 70, 84, 79, 64],
    [90, 86, 92, 88, 73],
    [58, 61, 55, 63, 49],
    [42, 38, 45, 40, 35]
])

# Daily canteen sales for two weeks
canteen_sales = np.array([
    [18500, 17200, 19300, 20100, 21400],
    [19200, 18100, 20500, 21800, 22500],
    [17600, 16900, 18800, 19600, 20800],
    [21000, 19800, 22100, 23000, 24200],
    [22500, 21400, 23800, 24600, 25500],
    [14200, 13600, 15100, 16000, 16800],
    [12500, 11900, 13200, 14100, 14800],
    [18900, 17800, 20100, 21000, 22000],
    [19500, 18400, 20800, 21900, 22800],
    [18100, 17300, 19200, 20200, 21100]
])

# Temperature readings from campus equipment
equipment_temperature = np.array(
    [24.5, 25.1, 23.8, 27.4, 29.2, 26.8, 31.5, 22.9, 28.1, 30.4]
)

months = np.array([
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
])

facilities = np.array(["Academic Block", "Library", "Hostel"])

print("Data loaded successfully.")


Data loaded successfully.


# Part A – Creating and Understanding Arrays

### Question 1 – A small campus record

The security department records the number of students entering the campus at five different times:

`[125, 180, 210, 165, 95]`

Create a NumPy array called `entry_count`.

Display:

1. The array
2. Its type
3. Its shape
4. Its data type


In [ ]:
# Write your code for Question 1 here
entry_count = np.array([125, 180, 210, 165, 95])
print(entry_count)

[125 180 210 165  95]


### Question 2 – Creating test data

The IT department needs some test data before connecting the real sensors.

Create:

1. A `3 × 4` array containing only zeros.
2. A `2 × 5` array containing random values between 0 and 1.
3. An array containing the numbers from 10 to 30 using `np.arange()`.

Display the three arrays.


In [ ]:
# Write your code for Question 2 here
zero_array = np.zeros((3, 4))
random_array = np.random.rand(2, 5)
range_array = np.arange(10, 31)
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Question 3 – Understanding dimensions

Create the following arrays:

- A 1D array containing the marks of 5 students.
- A 2D array containing marks of 3 students in 4 subjects.
- A 3D array containing data for 2 classes, where each class has 3 students and 2 test scores.

Print the shape of each array.

You do not need to print the complete 3D array if the output becomes difficult to read.


In [ ]:
# Write your code for Question 3 here
marks_1d = np.array([85, 92, 78, 90, 88])
print(marks_1d.shape)


(5,)


### Question 4 – Data type and memory

The classroom occupancy values are whole numbers.

1. Check the dtype of `weekly_occupancy`.
2. Convert the array to `np.int8`.
3. Store the result in `occupancy_int8`.
4. Print the dtype of the new array.

Why is an integer type suitable for this particular dataset? Write your answer in a comment.


In [ ]:
# Write your code for Question 4 here
print(weekly_occupancy.dtype)
occupancy_int8 = weekly_occupancy.astype(np.int8)
print(occupancy_int8.dtype)

int64
int8


# Part B – Indexing and Slicing

### Question 5 – Looking at one month's data

Using `monthly_energy`:

1. Display the electricity consumption of all three facilities for January.
2. Display the electricity consumption of the Library for January.
3. Display the electricity consumption of the Hostel for June.
4. Display the complete row for August.

Use NumPy indexing. Do not create a separate array manually for these values.


In [ ]:
# Write your code for Question 5 here
print(monthly_energy[0])
print(monthly_energy[0][1])
print(monthly_energy[5][2])
print(monthly_energy[7])

[42000 18500 31000]
18500
35200
[52500 24600 37100]


### Question 6 – Selecting a facility

The university wants to study the Academic Block separately.

Using `monthly_energy`:

1. Extract all 12 monthly values for the Academic Block.
2. Extract the first six months.
3. Extract the last three months.
4. Extract every second month starting from January.

Store the results in separate variables.


In [ ]:
# Write your code for Question 6 here
monthly_energy_ab = monthly_energy[:, 0]
print(monthly_energy_ab)

[42000 43500 44800 46200 47800 49500 51000 52500 51800 50200 47500 45000]


### Question 7 – Selecting multiple months

The management committee is reviewing the summer period.

Using `monthly_energy`, extract the data for:

- May
- June
- July
- August

Display the resulting 4 × 3 array.


In [ ]:
# Write your code for Question 7 her
monthly_energy_summer = monthly_energy[4:8]
print(monthly_energy_summer)

[[47800 22100 34000]
 [49500 23000 35200]
 [51000 23800 36000]
 [52500 24600 37100]]


### Question 8 – Working with classroom data

Using `weekly_occupancy`:

1. Display the occupancy of all five classrooms on the first day.
2. Display the occupancy of Classroom 3 for all seven days.
3. Display the first three classrooms for the first five days.
4. Display every second row of the occupancy array.

Pay attention to zero-based indexing.


In [ ]:
# Write your code for Question 8 here
print(weekly_occupancy[0])
print(weekly_occupancy[:, 2])
print(weekly_occupancy[:3, :3])
print(weekly_occupancy[::2])

[72 68 81 75 63]
[81 85 88 84 92 55 45]
[[72 68 81]
 [78 71 85]
 [82 74 88]]
[[72 68 81 75 63]
 [82 74 88 83 69]
 [90 86 92 88 73]
 [42 38 45 40 35]]


# Part C – Sorting and Filtering

### Question 9 – Sorting temperature readings

The maintenance team wants to see equipment temperatures from lowest to highest.

Using `equipment_temperature`:

1. Sort the readings using `np.sort()`.
2. Display the three lowest readings.
3. Display the three highest readings.

Do not use Python's built-in `sorted()` function.


In [ ]:
# Write your code for Question 9 here
equipment_temperature_sorted = np.sort(equipment_temperature)
print(equipment_temperature_sorted[:3])
print(equipment_temperature_sorted[-3:])

[22.9 23.8 24.5]
[29.2 30.4 31.5]


### Question 10 – Finding high-temperature equipment

The maintenance department considers a reading above **28°C** to be a warning.

Using `equipment_temperature`:

1. Create a Boolean mask for temperatures above 28°C.
2. Display the mask.
3. Use the mask to display only the warning readings.
4. Count how many warning readings are present.


In [ ]:
# Write your code for Question 10 here
mask = equipment_temperature > 28
print(mask)
print(equipment_temperature[mask])
print(np.sum(mask))

[False False False False  True False  True False  True  True]
[29.2 31.5 28.1 30.4]
4


### Question 11 – Finding highly occupied classrooms

A classroom is considered **highly occupied** when its occupancy is at least 80%.

Using `weekly_occupancy`:

1. Create a Boolean condition for values greater than or equal to 80.
2. Use Boolean indexing to extract all occupancy values meeting this condition.
3. Display how many such values are present.


In [ ]:
# Write your code for Question 11 here
condition = weekly_occupancy >= 80
print(weekly_occupancy[condition])
print(np.sum(condition))

[81 85 80 82 88 83 84 90 86 92 88]
11


### Question 12 – Finding high electricity consumption

The university wants to identify all months in which the Academic Block consumed more than **50,000 kWh**.

Using NumPy:

1. Create a condition.
2. Use Boolean indexing to get the corresponding energy values.
3. Use `np.where()` to find their positions.
4. Use those positions with the `months` array to find the month names.


In [ ]:
# Write your code for Question 12 here
condition = monthly_energy[:, 0] > 50000
print(monthly_energy[condition, 0])
print(np.where(condition))
print(months[np.where(condition)])

[51000 52500 51800 50200]
(array([6, 7, 8, 9]),)
['Jul' 'Aug' 'Sep' 'Oct']


# Part D – `np.where()` and Conditional Values

### Question 13 – Classify classroom occupancy

For a simple campus report:

- 80% or above → `"High"`
- Below 80% → `"Normal"`

Take the occupancy values of the **first classroom** from `weekly_occupancy`.

Use `np.where()` to create a new array called `classroom_status`.

Display both the occupancy values and their status.


In [ ]:
# Write your code for Question 13 here
classroom_status = np.where(weekly_occupancy[:, 0] >= 80, "High", "Normal")
print(weekly_occupancy[:, 0])
print(classroom_status)

[72 78 82 76 90 58 42]
['Normal' 'Normal' 'High' 'Normal' 'High' 'Normal' 'Normal']


### Question 14 – Energy saving alert

The university wants to label monthly Academic Block consumption:

- More than 50,000 kWh → `"Check"`
- Otherwise → `"OK"`

Use `np.where()` and store the result in `energy_status`.

Display the month, energy value and status separately.


In [ ]:
# Write your code for Question 14 here
energy_status = np.where(monthly_energy[:, 0] > 50000, "Check", "OK")
print(months)
print(monthly_energy[:, 0])
print(energy_status)

['Jan' 'Feb' 'Mar' 'Apr' 'May' 'Jun' 'Jul' 'Aug' 'Sep' 'Oct' 'Nov' 'Dec']
[42000 43500 44800 46200 47800 49500 51000 52500 51800 50200 47500 45000]
['OK' 'OK' 'OK' 'OK' 'OK' 'OK' 'Check' 'Check' 'Check' 'Check' 'OK' 'OK']


### Question 15 – Combining two measurements

For each month, the operations team wants to use the actual electricity consumption when it is available. If the value is 0, it should use a backup estimate.

Create two small NumPy arrays:

```text
actual = [42000, 0, 44800, 0, 47800]
backup = [41000, 43000, 44000, 45500, 47000]
```

Use `np.where()` to create a final array that:

- uses `backup` when `actual` is 0,
- otherwise uses `actual`.


In [ ]:
# Write your code for Question 15 here
actual = np.array([42000, 0, 44800, 0, 47800])
backup = np.array([41000, 43000, 44000, 45500, 47000])
final_array = np.where(actual == 0, backup, actual)
print(final_array)

[42000 43000 44800 45500 47800]


# Part E – Concatenating and Deleting Data

### Question 16 – Adding a new facility

A new **Sports Complex** has been added to the campus.

Its monthly electricity consumption is:

`[12500, 13000, 12800, 13500, 14200, 15000, 15800, 16200, 15500, 14800, 13700, 12900]`

1. Convert the data into a NumPy array.
2. Reshape it into a single column.
3. Add it to `monthly_energy` using `np.concatenate()` with the correct axis.
4. Store the final array as `energy_with_sports`.
5. Check its shape.


In [ ]:
import numpy as np

# Re-defining monthly_energy here to ensure it's the correct 2D array.
# This is a workaround if the original setup cell was not run or if
# monthly_energy was inadvertently overwritten as a scalar.
monthly_energy = np.array([
    [42000, 18500, 31000],
    [43500, 19200, 31800],
    [44800, 20100, 32500],
    [46200, 21500, 33100],
    [47800, 22100, 34000],
    [49500, 23000, 35200],
    [51000, 23800, 36000],
    [52500, 24600, 37100],
    [51800, 24100, 36500],
    [50200, 23200, 35400],
    [47500, 21800, 33900],
    [45000, 20500, 32500]
])

# Write your code for Question 16 here

sports_complex = np.array([12500, 13000, 12800, 13500, 14200, 15000,
                           15800, 16200, 15500, 14800, 13700, 12900])

sports_complex = sports_complex.reshape(-1, 1)

energy_with_sports = np.concatenate((monthly_energy, sports_complex), axis=1)

print(energy_with_sports)
print(energy_with_sports.shape)

[[42000 18500 31000 12500]
 [43500 19200 31800 13000]
 [44800 20100 32500 12800]
 [46200 21500 33100 13500]
 [47800 22100 34000 14200]
 [49500 23000 35200 15000]
 [51000 23800 36000 15800]
 [52500 24600 37100 16200]
 [51800 24100 36500 15500]
 [50200 23200 35400 14800]
 [47500 21800 33900 13700]
 [45000 20500 32500 12900]]
(12, 4)


### Question 17 – Adding a new month

Suppose the university receives data for one additional month:

`[46500, 21000, 33000]`

Add this as a new row to `monthly_energy` using `np.concatenate()`.

Store the result as `energy_extended`.

Check its shape before and after concatenation.


In [ ]:
# Write your code for Question 17 here
monthly_energy_new = np.array([46500, 21000, 33000])
energy_extended = np.concatenate((monthly_energy, monthly_energy_new.reshape(1, -1)), axis=0)

### Question 18 – Removing a column

For one report, the Hostel data is not required.

Use `np.delete()` to remove the Hostel column from `monthly_energy`.

Store the result as `energy_without_hostel`.

Display the new shape.

Do not change the original `monthly_energy` array.


In [ ]:
# Write your code for Question 18 here
energy_without_hostel = np.delete(monthly_energy, 2, axis=1)
print(energy_without_hostel.shape)

(12, 2)


# Part F – Mathematical Operations

### Question 19 – Electricity bill

The electricity rate is **₹8.50 per kWh**.

Use vectorized multiplication to calculate the monthly electricity bill for all three facilities.

Store the result as `monthly_bill`.

Display the bill for the first three months.


In [ ]:
# Write your code for Question 19 here
monthly_bill = monthly_energy * 8.5
print(monthly_bill[:3])

[[357000. 157250. 263500.]
 [369750. 163200. 270300.]
 [380800. 170850. 276250.]]


### Question 20 – Monthly totals

The management wants to know how much electricity was consumed across the entire campus each month.

Using `monthly_energy`:

1. Calculate the total consumption for each month.
2. Store it as `monthly_total`.
3. Find the highest monthly campus consumption using `np.max()`.
4. Find the lowest monthly campus consumption.

Use an appropriate `axis`.


In [ ]:
# Write your code for Question 20 here
monthly_total = np.sum(monthly_energy, axis=1)
print(monthly_total)
print(np.max(monthly_total))
print(np.min(monthly_total))

[ 91500  94500  97400 100800 103900 107700 110800 114200 112400 108800
 103200  98000]
114200
91500


### Question 21 – Average consumption

Find the average electricity consumption of:

- Academic Block
- Library
- Hostel

Calculate one average value for each facility.

Use the appropriate axis and store the result as `average_facility_energy`.

Then display the facility names along with their average consumption.


In [ ]:
# Write your code for Question 21 here
average_facility_energy = np.mean(monthly_energy, axis=0)
print(average_facility_energy)

[47650.         21866.66666667 34083.33333333]


### Question 22 – Student visits

Using `monthly_visits`:

1. Find the total yearly visits for each facility.
2. Find the average monthly visits for each facility.
3. Find the month with the highest total campus visits.
4. Display that month's name and total number of visits.

Use NumPy operations rather than loops.


In [ ]:
# Write your code for Question 22 here
yearly_visits = np.sum(monthly_visits, axis=0)
print(yearly_visits)
average_monthly_visits = np.mean(monthly_visits, axis=0)
print(average_monthly_visits)

[111700  73750  82150]
[9308.33333333 6145.83333333 6845.83333333]


### Question 23 – Cumulative electricity consumption

The finance department wants a running total of electricity consumption throughout the year.

Use `cumsum(axis=0)` on `monthly_energy`.

Display:

1. The cumulative values for January, February and March.
2. The final cumulative value for each facility.

Think about why `axis=0` is suitable here.


In [ ]:
# Write your code for Question 23 here
cumulative_energy = np.cumsum(monthly_energy, axis=0)
print(cumulative_energy[:3])
print(cumulative_energy[:, 0])

[[ 42000  18500  31000]
 [ 85500  37700  62800]
 [130300  57800  95300]]
[ 42000  85500 130300 176500 224300 273800 324800 377300 429100 479300
 526800 571800]


# Part G – Broadcasting

### Question 24 – Applying a monthly adjustment

During summer, electricity consumption is expected to increase.

The estimated monthly adjustment factors are:

`[0.95, 0.96, 0.98, 1.00, 1.02, 1.05, 1.08, 1.10, 1.06, 1.02, 0.98, 0.96]`

1. Create a NumPy array containing these factors.
2. Reshape it so that its shape becomes `(12, 1)`.
3. Use broadcasting to multiply it with `monthly_energy`.
4. Store the result as `adjusted_energy`.
5. Print both shapes.

Do not manually create a 12 × 3 array of factors.


In [ ]:
# Write your code for Question 24 here

monthly_adjustment_factors = np.array([0.95, 0.96, 0.98, 1.00, 1.02, 1.05, 1.08, 1.10, 1.06, 1.02, 0.98, 0.96])
monthly_adjustment_factors_reshaped = monthly_adjustment_factors.reshape(-1, 1)

adjusted_energy = monthly_energy * monthly_adjustment_factors_reshaped

print(monthly_energy.shape)
print(monthly_adjustment_factors_reshaped.shape)
print(adjusted_energy.shape)
print(adjusted_energy)

(12, 3)
(12, 1)
(12, 3)
[[39900. 17575. 29450.]
 [41760. 18432. 30528.]
 [43904. 19698. 31850.]
 [46200. 21500. 33100.]
 [48756. 22542. 34680.]
 [51975. 24150. 36960.]
 [55080. 25704. 38880.]
 [57750. 27060. 40810.]
 [54908. 25546. 38690.]
 [51204. 23664. 36108.]
 [46550. 21364. 33222.]
 [43200. 19680. 31200.]]


### Question 25 – Facility-specific adjustment

The university is planning energy-saving measures.

The expected adjustment factors are:

- Academic Block → `0.90`
- Library → `0.95`
- Hostel → `0.88`

Create a NumPy array of these three factors.

Use broadcasting to apply the factors to every month of `monthly_energy`.

Store the result as `target_energy`.

Check the shape of the factor array and the resulting array.


In [ ]:
# Write your code for Question 25 here

adjustment_factors = np.array([0.90, 0.95, 0.88])
target_energy = monthly_energy * adjustment_factors.reshape(1, -1)
print(adjustment_factors.shape)
print(target_energy.shape)
print(target_energy)

(3,)
(12, 3)
[[37800. 17575. 27280.]
 [39150. 18240. 27984.]
 [40320. 19095. 28600.]
 [41580. 20425. 29128.]
 [43020. 20995. 29920.]
 [44550. 21850. 30976.]
 [45900. 22610. 31680.]
 [47250. 23370. 32648.]
 [46620. 22895. 32120.]
 [45180. 22040. 31152.]
 [42750. 20710. 29832.]
 [40500. 19475. 28600.]]


### Question 26 – Applying a common increase

The university expects student visits to increase by **5%** next year.

Using `monthly_visits`, calculate the projected number of visits after a 5% increase.

Store the result as `projected_visits`.

Display the projected visits for the first three months.


In [ ]:
# Write your code for Question 26 here
projected_visits = monthly_visits * 1.05
print(projected_visits[:3])

[[8610.  5670.  6405. ]
 [8925.  5880.  6562.5]
 [9135.  6037.5 6720. ]]


# Part H – Reshape and Flatten

### Question 27 – Preparing attendance data

Create the following attendance array:

`[82, 75, 91, 88, 79, 95, 84, 73, 89, 92, 86, 80]`

1. Check its shape.
2. Reshape it into a `3 × 4` array.
3. Display the reshaped array.
4. Flatten it again using `flatten()`.
5. Check its shape.

Notice that reshaping changes the arrangement, but not the number of values.


In [ ]:
# Write your code for Question 27 here
attendance = np.array([82, 75, 91, 88, 79, 95, 84, 73, 89, 92, 86, 80])
print(attendance.shape)
attendance_reshaped = attendance.reshape(3, 4)
print(attendance_reshaped)
attendance_flattened = attendance_reshaped.flatten()
print(attendance_flattened)
print(attendance_flattened.shape)

(12,)
[[82 75 91 88]
 [79 95 84 73]
 [89 92 86 80]]
[82 75 91 88 79 95 84 73 89 92 86 80]
(12,)


### Question 28 – Reshaping campus sales data

Take the first 6 values from the first row of `canteen_sales`.

Reshape those six values into a `2 × 3` array.

Display the original selected values and the reshaped array.


In [ ]:
# Write your code for Question 28 here

# The problem statement requests 'first 6 values' and 'reshape into a 2x3 array',
# which requires 6 elements. Since canteen_sales[0] only has 5 elements,
# we will take all 5 from the first row and the first element from the second row
# to form a 6-element array for reshaping.
selected_canteen_sales = np.concatenate((canteen_sales[0, :], canteen_sales[1, :1]))
print("Original selected values (derived for 2x3 reshape):", selected_canteen_sales)

reshaped_canteen_sales = selected_canteen_sales.reshape(2, 3)
print("Reshaped array (2x3):")
print(reshaped_canteen_sales)

Original selected values (derived for 2x3 reshape): [18500 17200 19300 20100 21400 19200]
Reshaped array (2x3):
[[18500 17200 19300]
 [20100 21400 19200]]


# Part I – Transpose, Split and File Handling

### Question 29 – Change the view of classroom data

The weekly occupancy data currently has:

- rows → days
- columns → classrooms

Transpose `weekly_occupancy` so that:

- rows represent classrooms
- columns represent days

Store the result as `occupancy_by_classroom`.

Display its shape and the first row.


In [ ]:
# Write your code for Question 29 here
occupancy_by_classroom = np.transpose(weekly_occupancy)
print(occupancy_by_classroom.shape)
print(occupancy_by_classroom[0])

(5, 7)
[72 78 82 76 90 58 42]


### Question 30 – Divide the year into quarters

The annual electricity data contains 12 months.

Use `np.split()` to divide `monthly_energy` into four equal parts representing:

- Q1
- Q2
- Q3
- Q4

Store them as `q1`, `q2`, `q3` and `q4`.

Display the shape of each quarter and the data for Q1.


In [ ]:
# Write your code for Question 30 here
q1, q2, q3, q4 = np.split(monthly_energy, 4)
print(q1.shape)
print(q2.shape)
print(q3.shape)
print(q4.shape)
print(q1)

(3, 3)
(3, 3)
(3, 3)
(3, 3)
[[42000 18500 31000]
 [43500 19200 31800]
 [44800 20100 32500]]


### Question 31 – Save and load NumPy data

The university wants to save its cleaned occupancy data for use in another notebook.

1. Save `weekly_occupancy` as `weekly_occupancy.npy` using `np.save()`.
2. Load the file using `np.load()`.
3. Store the loaded data as `loaded_occupancy`.
4. Display its shape.
5. Check whether the loaded array is equal to the original array.

This question is about using NumPy's own `.npy` format.


In [ ]:
# Write your code for Question 31 here
np.save("weekly_occupancy.npy", weekly_occupancy)
loaded_occupancy = np.load("weekly_occupancy.npy")
print(loaded_occupancy.shape)
print(np.array_equal(weekly_occupancy, loaded_occupancy))

(7, 5)
True


# Final Case Study Questions

### Question 32 – Which facility uses the most electricity?

Use `monthly_energy` to find the facility with the highest total yearly electricity consumption.

Your program should:

1. Calculate the yearly total for each facility.
2. Find the position of the highest value.
3. Use that position to find the facility name.
4. Display the facility name and its total consumption.

Do not use a Python loop.


In [ ]:
# Write your code for Question 32 here
yearly_total = np.sum(monthly_energy, axis=0)
max_position = np.argmax(yearly_total)
facility_names = ["Academic Block", "Library", "Hostel"]
facility_name = facility_names[max_position]
print(facility_name, yearly_total[max_position])


Academic Block 571800


### Question 33 – Which month was busiest?

Using `monthly_visits`:

1. Calculate total campus visits for every month.
2. Find the index of the month with the highest total visits.
3. Display the month name.
4. Display the total number of visits.

Try to solve the complete question using NumPy.


In [ ]:
# Write your code for Question 33 here
month_names = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]

total_monthly_visits = np.sum(monthly_visits, axis=1)
max_position = np.argmax(total_monthly_visits)

busiest_month_name = month_names[max_position]
highest_total_visits = total_monthly_visits[max_position]

print(f"Busiest Month: {busiest_month_name}")
print(f"Total Visits: {highest_total_visits}")

Busiest Month: August
Total Visits: 25100


### Question 34 – Find classrooms that need attention

The university wants to identify classrooms where occupancy was **below 50% at least once** during the week.

Using `weekly_occupancy`:

1. Find the occupancy values below 50%.
2. Find the corresponding positions using NumPy.
3. Identify which classroom columns are involved.
4. Display the result clearly.

You may use indexing, Boolean masks and `np.where()`.


In [ ]:
# Write your code for Question 34 here
below_50_mask = weekly_occupancy < 0.5
classroom_positions = np.where(below_50_mask)
print(below_50_mask,classroom_positions)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]] (array([], dtype=int64), array([], dtype=int64))


### Question 35 – Energy efficiency check

The university wants to compare electricity consumption with student visits.

For each facility:

1. Calculate total yearly electricity consumption.
2. Calculate total yearly student visits.
3. Calculate electricity consumption per student visit.
4. Display the three resulting values.
5. Identify the facility with the highest electricity consumption per visit.

Use vectorized NumPy operations.

This is the final step of the case study: turning raw numerical arrays into a simple decision that can help campus management.


In [ ]:
# Write your code for Question 35 here
yearly_electricity_consumption = np.sum(monthly_energy, axis=0)
yearly_student_visits = np.sum(monthly_visits, axis=0)
electricity_consumption_per_visit = yearly_electricity_consumption / yearly_student_visits
print(electricity_consumption_per_visit)
max_position = np.argmax(electricity_consumption_per_visit)
print(facility_names[max_position])

[5.11906893 3.5579661  4.9786975 ]
Academic Block


## Quick Check Before You Finish

Make sure you have practised the following NumPy operations in this notebook:

- `np.array()`
- `np.zeros()`
- `np.random.random()`
- `np.arange()`
- `.shape`
- `.dtype`
- `.astype()`
- `.flatten()`
- `.reshape()`
- Indexing
- Slicing
- Boolean indexing
- `np.sort()`
- `np.where()`
- `np.concatenate()`
- `np.delete()`
- Vectorized arithmetic
- `np.max()`
- `mean()`
- `sum()`
- `cumsum()`
- Broadcasting
- `np.flip()`
- `transpose()`
- `np.split()`
- `np.save()`
- `np.load()`

### Final Reminder

Focus on understanding **why** an operation is being used, not just on getting an output. In NumPy, always keep an eye on the **shape of the array**, especially before reshaping, concatenating or broadcasting.
